#!/bin/bash

DIR="${BLOCK_INSTANCE:-$HOME}"

DATA=$(df -h --output=avail,pcent,target $DIR | tail -n1)
if [[ -z "$DATA" ]]; then
	echo "Device"
	echo "D"
	echo "#FF0000"
	exit
fi

AVAIL=$(echo $DATA | awk '{print $1}')
USED=$(echo $DATA | awk '{print $2}' | tr -d %)
TARGET=$(echo $DATA | awk '{print $3}')

if ! [[ "$DIR" == "$TARGET" ]]; then
	exit
fi

echo $AVAIL
echo $AVAIL

if [[ $USED -gt 90 ]]; then
	echo "#FFFF00"
elif [[ $USED -gt 95 ]]; then
	echo "#FF0000"
fi
