#!/usr/bin/env python3
from datetime import datetime

time_data = [
	[
		"One o’clock",
		"Five past one",
		"Ten past one",
		"Quarter past one",
		"Twenty past one",
		"Twenty-five past one",
		"Half past one",
		"Twenty-five to two",
		"Twenty to two",
		"Quarter to two",
		"Ten to two",
		"Five to two"
	],
	[
		"Two o’clock",
		"Five past two",
		"Ten past two",
		"Quarter past two",
		"Twenty past two",
		"Twenty-five past two",
		"Half past two",
		"Twenty-five to three",
		"Twenty to three",
		"Quarter to three",
		"Ten to three",
		"Five to three"
	],
	[
		"Three o’clock",
		"Five past three",
		"Ten past three",
		"Quarter past three",
		"Twenty past three",
		"Twenty-five past three",
		"Half past three",
		"Twenty-five to four",
		"Twenty to four",
		"Quarter to four",
		"Ten to four",
		"Five to four"
	],
	[
		"Four o’clock",
		"Five past four",
		"Ten past four",
		"Quarter past four",
		"Twenty past four",
		"Twenty-five past four",
		"Half past four",
		"Twenty-five to five",
		"Twenty to five",
		"Quarter to five",
		"Ten to five",
		"Five to five"
	],
	[
		"Five o’clock",
		"Five past five",
		"Ten past five",
		"Quarter past five",
		"Twenty past five",
		"Twenty-five past five",
		"Half past five",
		"Twenty-five to six",
		"Twenty to six",
		"Quarter to six",
		"Ten to six",
		"Five to six"
	],
	[
		"Six o’clock",
		"Five past six",
		"Ten past six",
		"Quarter past six",
		"Twenty past six",
		"Twenty-five past six",
		"Half past six",
		"Twenty-five to seven",
		"Twenty to seven",
		"Quarter to seven",
		"Ten to seven",
		"Five to seven"
	],
	[
		"Seven o’clock",
		"Five past seven",
		"Ten past seven",
		"Quarter past seven",
		"Twenty past seven",
		"Twenty-five past seven",
		"Half past seven",
		"Twenty-five to eight",
		"Twenty to eight",
		"Quarter to eight",
		"Ten to eight",
		"Five to eight"
	],
	[
		"Eight o’clock",
		"Five past eight",
		"Ten past eight",
		"Quarter past eight",
		"Twenty past eight",
		"Twenty-five past eight",
		"Half past eight",
		"Twenty-five to nine",
		"Twenty to nine",
		"Quarter to nine",
		"Ten to nine",
		"Five to nine"
	],
	[
		"Nine o’clock",
		"Five past nine",
		"Ten past nine",
		"Quarter past nine",
		"Twenty past nine",
		"Twenty-five past nine",
		"Half past nine",
		"Twenty-five to ten",
		"Twenty to ten",
		"Quarter to ten",
		"Ten to ten",
		"Five to ten"
	],
	[
		"Ten o’clock",
		"Five past ten",
		"Ten past ten",
		"Quarter past ten",
		"Twenty past ten",
		"Twenty-five past ten",
		"Half past ten",
		"Twenty-five to eleven",
		"Twenty to eleven",
		"Quarter to eleven",
		"Ten to eleven",
		"Five to eleven"
	],
	[
		"Eleven o’clock",
		"Five past eleven",
		"Ten past eleven",
		"Quarter past eleven",
		"Twenty past eleven",
		"Twenty-five past eleven",
		"Half past eleven",
		"Twenty-five to twelve",
		"Twenty to twelve",
		"Quarter to twelve",
		"Ten to twelve",
		"Five to twelve"
	],
	[
		"Twelve o’clock",
		"Five past twelve",
		"Ten past twelve",
		"Quarter past twelve",
		"Twenty past twelve",
		"Twenty-five past twelve",
		"Half past twelve",
		"Twenty-five to one",
		"Twenty to one",
		"Quarter to one",
		"Ten to one",
		"Five to one"
	],
]

now   = datetime.now()
hours = now.hour
mins  = now.minute

# magic formula from FuzzyClock.qml
sector = ((mins + 7) / 15 * 3)
sector = sector - (sector % 3)
sector = int(sector)

# if the sector is at max, carry the 1
if sector == 12:
	hours += 1
	sector = 0

hours = (hours % 12 - 1)
if hours == -1: hours = 11

fuzzy_str = time_data[hours][sector]
fuzzy_num = '~{}:{}'.format(
	str(now.hour).zfill(2),
	str(sector * 5).zfill(2),
)

print(fuzzy_str + ' ')
print(fuzzy_num + ' ')
