#!/bin/bash

LAYOUT=$(setxkbmap -query | grep '^layout:' | awk '{print $2}')

VARIANT=$(setxkbmap -query | grep '^variant:' | awk '{print $1}')
if [ "$VARIANT" = "variant:" ]; then
	VARIANT=$(setxkbmap -query | grep '^variant:' | awk '{print $2}' | sed -E 's/^/: /')
fi

#COLOR=\#FFFF00
if [[ "$LAYOUT$VARIANT" == "us: dvorak" ]] && [[ $(hostname) != Desktop ]]; then
#	COLOR=\#808080
	exit
fi

if [[ "$LAYOUT$VARIANT" == "us" ]] && [[ $(hostname) == Desktop ]]; then
#	COLOR=\#808080
	exit
fi

echo $LAYOUT$VARIANT
echo $LAYOUT$VARIANT
#echo $COLOR
echo \#FFFF00
