#!/bin/bash

# if mpd is not running
if [[ -z "$(mpc status)" ]]; then
	systemctl --user start mpd
	echo Down
	echo Down
	echo "#FF0000"
	exit
fi

STATE=$(mpc | grep -Eo '^\[(playing|paused)\]' | tr -d '[]')
[[ -z $STATE ]] && exit
VOLUME="$(mpc volume | cut -c8- | tr -d ' ')"

DATA="$VOLUME"

echo "$DATA"
echo "$DATA"

[[ $STATE -eq playing ]] && echo "#00CC00"
[[ $STATE -eq paused  ]] && echo "#FFFF00"
