#!/bin/bash

# if mpd is not running
if [[ -z "$(mpc status)" ]]; then
	systemctl --user start mpd
	echo Down
	echo Down
	echo "#FF0000"
fi

STATE=$(mpc | grep -Eo '^\[(playing|paused)\]' | tr -d '[]')
activate() {
	if [[ -z "$STATE" ]]; then
		~/bin/mpdsat
	else
		mpc toggle
	fi
}

VOLUME="$(mpc volume | cut -c8- | tr -d ' ')"
STATE=$(mpc | grep -Eo '^\[(playing|paused)\]' | tr -d '[]')

OUTPUT="$VOLUME"

if [[ $OUTPUT == 'n/a' ]]; then
	OUTPUT='*'
	exit
fi

echo "$OUTPUT"
echo "$OUTPUT"

if [[ -z "$STATE" ]]; then
	echo "#999999"
elif [[ "$STATE" = "playing" ]]; then
	echo "#00CC00"
elif [[ "$STATE" = "paused" ]]; then
	echo "#FFFF00"
fi
