#!/bin/bash
pac="$(checkupdates)"
aur="$(cower -u --ignore "libc++,libc++abi")"
#aur="$(echo -e)"
pacn="$(echo "$pac" | wc -l)"
aurn="$(echo "$aur" | wc -l)"

if ! [[ $pac ]]; then
	pacn="0"
fi
if ! [[ $aur ]]; then
	aurn="0"
fi
check="$(($pacn+$aurn))"
linux="$(echo "$pac" | grep -c linux)"

if [[ $check == 0 ]]; then
	exit
fi

text="$check"
if [[ $aur ]]; then
	text="$text/$aurn"
fi
if [[ $linux != "0" ]]; then
	text="$text!"
fi

echo $text
echo $text

if [[ $check -gt 50 ]]; then
	echo "#FF0000"
elif [[ $check -gt 25 ]]; then
	echo "#FFFF00"
elif [[ $check == 0 ]]; then
	echo "#00FF00"
fi
