#!/bin/bash
PAC="$(checkupdates)"
AUR="$(cower -u --ignore "libc++,libc++abi")"
PACN="$(echo "$PAC" | wc -l)"
AURN="$(echo "$AUR" | wc -l)"

if ! [[ $PAC ]]; then
	PACN="0"
fi
if ! [[ $AUR ]]; then
	AURN="0"
fi
CHECK="$(($PACN+$AURN))"
LINUX="$(echo "$PAC" | grep -c linux)"

if [[ $CHECK == 0 ]]; then
	exit
fi

text="$CHECK"
if [[ $AUR ]]; then
	text="$text/$AURN"
fi
if [[ $LINUX != "0" ]]; then
	text="$text!"
fi

echo $text
echo $text

if [[ $CHECK -gt 50 ]]; then
	echo "#FF0000"
elif [[ $CHECK -gt 25 ]]; then
	echo "#FFFF00"
elif [[ $CHECK == 0 ]]; then
	echo "#00FF00"
fi
